### ISSUE TITLE
Couldn't unbind nf_queue handler for AF_INET

### ISSUE THREAD

**Issue by nijikon** [zevenet/packetbl#1]
I tried to compile and start, but I'm getting this.
```
root@mx:~/packetbl# packetbl -f /root/packetbl/packetbl.conf -d 5
Debug level 5
Linking to queue 0
Creating nfq handle...
unbinding nfq handle...
Couldn't unbind nf_queue handler for AF_INET
```

**Comment by emiliocampos-zevenet** [comment]
Hi nijikon, could you share more information about your current config? 

Please paste the config file /root/packetbl/packetbl.conf 

and loaded modules with the following command:

lsmod

Thanks

**Comment by nijikon** [comment]
Config is here https://gist.github.com/nijikon/59acfd27f75e0bd7260e50e4586f0a4d.

I'm running this on debian jessie. Don't have `lsmod`.

**Comment by nijikon** [comment]
I updated the gist with config.log

**Comment by emiliocampos-zevenet** [comment]
Hi jijkon, lsmod is needed in order to confirm your system loaded all the required netfilter modules, you can install lsmod binary with the following package, check url:

https://packages.debian.org/search?suite=jessie&arch=any&mode=path&searchon=contents&keywords=lsmod

Also please confirm you configured the proper iptable rule in order to forward smtp traffic to userspace, for example:

iptables -A INPUT -t filter -p tcp --dport 25 -j NFQUEUE --queue-num 0

This iptable rule forwards to userspace queue 0 the packets (queue 0 is where packetbl is listening). I gess that your smtp server is in the same machine where packetbl is running right? If your packetb is in the firewall then the iptables rule should change a little bit.

**Comment by emiliocampos-zevenet** [comment]
Checking attached config.log file seems like some needed libraries are not found in system, did you install library dependencies for Jessie? README indicates needed dependencies, copied and pasted:

jessie
libdotconf0 libldns1 libnetfilter-queue1 libnfnetlink0 libdotconf-dev

Please confirm.

**Comment by nijikon** [comment]
Actually, I wrote it wrong, it's `stretch` with `sid`. So i installed this.
```
root@mx:/# apt-get install libdotconf0 libldns2 libnetfilter-queue1 libnfnetlink0 libdotconf-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libdotconf-dev is already the newest version (1.3-0.2).
libdotconf0 is already the newest version (1.3-0.2).
libnetfilter-queue1 is already the newest version (1.0.2-2).
libldns2 is already the newest version (1.7.0-3).
libnfnetlink0 is already the newest version (1.0.1-3+b1).
```

I didn't configure the `iptables`, should that be create before starting `packetbl`? Also, I think it's worth mentioning that I run this in a `vserver` container.

**Comment by alvarocano-zevenet** [comment]
Hi nijikon, Packetbl uses a Linux kernel module called nfnetlink_queue, then it is necessary to know if it is running in your system. Try to install lsmod command and check it `lsmod | grep nfnetlink_queue`

**Comment by emiliocampos-zevenet** [comment]
Not enough information, it seems like there are pending dependencies not installed, required to compile packetbl.
